/* Handbuch – Seiten {id, title, html}. Wird mit den Themen erweitert. */
(function (root) {
  'use strict';
  root.DQ.manual = [
    { id: 'bedienung', title: 'Bedienung', html:
      '<p><b>Bauteil hinzufügen:</b> Klick in der Palette. <b>Verschieben:</b> ziehen. <b>Drehen:</b> <kbd>R</kbd>. <b>Löschen:</b> <kbd>Entf</kbd>.</p>' +
      '<p><b>Leitung ziehen:</b> Anschluss anklicken, dann den Ziel-Anschluss. Leitung anklicken und <kbd>Entf</kbd> entfernt sie.</p>' +
      '<p><b>Schalter</b> schaltest du per Klick, <b>Taster</b> sind nur gedrückt, solange du sie hältst.</p>' +
      '<p>Die Schaltung wird <b>laufend simuliert</b>. „U anzeigen“ färbt alle Knoten nach ihrer Spannung (blau = 0 V, rot = höchste Spannung). Fährst du über ein Bauteil, siehst du U, I und P.</p>' +
      '<p><b>Messen auf der Werkbank:</b> Messspitzen (rot = +, schwarz = COM) und den Tastkopf des Oszilloskops mit der Maus an die Buchsen <b>ziehen</b>; daneben loslassen legt sie zurück. Im Schaltplan setzt ein Klick die Spitze. In den Messtechnik-Aufgaben (Kapitel 16) wählst du zusätzlich den <b>Messbereich</b> am Gerät – zu klein zeigt OL. Jede Messaufgabe hat oben die Box „So stellst du das Gerät ein“. Zoom auf der Werkbank: <kbd>Strg</kbd> + Mausrad, Verschieben durch Ziehen auf der leeren Tischfläche; das Mausrad allein scrollt die Seite.</p>' +
      '<p><b>Schaltplan oder Werkbank:</b> Der Knopf „Werkbank“ / „Schaltplan“ wechselt die Darstellung. Es ist dieselbe Schaltung – auf der Werkbank stecken die Bauteile auf Steckbausteinen und werden mit Laborkabeln verbunden. Bauen, Messen und Prüfen funktionieren in beiden Ansichten gleich. Auf der Werkbank zoomst du mit dem Mausrad (Handy: zwei Finger) und verschiebst den Tisch, indem du auf einer freien Stelle ziehst; „Einpassen“ zeigt wieder alles.</p>' +
      '<p><b>Zeitlupe:</b> zeigt Schritt für Schritt, wie die Simulation zum Ergebnis kommt – welche LED leitend wird, welches Gatter umschaltet, wie sich ein Kondensator über die Zeit lädt. Mit dem Schieberegler oder den Pfeiltasten blättern, „Live“ kehrt zurück.</p>' +
      '<p><b>Strom zeigen</b> („⇢ Strom“ in der Werkzeugleiste): Punkte wandern entlang der Leitungen in <b>technischer Stromrichtung</b> (von + nach −) – je schneller, desto mehr Strom. An jedem Kabel steht der Stromwert. So siehst du, wo sich der Strom aufteilt und wo gar keiner fliesst.</p>' +
      '<p><b>Freie Werkbank:</b> auf der Karte. Bauen und messen ohne Auftrag, mit allen bisher freigeschalteten Bauteilen.</p>' +
      '<p><b>Limits:</b> Manche Aufgaben erlauben nur eine bestimmte Anzahl Gatter („Erlaubt: höchstens 3 Logikgatter“). Die Prüfung zählt mit.</p>' },
    { id: 'konto', title: 'Konto, Portal und Vorgaben', html:
      '<p>Ein <b>Konto ist freiwillig</b>. Ohne Konto spielst du ganz normal, der Fortschritt bleibt auf diesem Gerät (auch offline). Angemeldet wird im <b>Portal</b> (Startseite): mit Benutzername und Passwort oder – beim ersten Mal – mit dem <b>Klassencode</b> deiner Lehrperson. Oben rechts im Labor zeigt der <b>Konto-Knopf</b>, wer angemeldet ist; ein Klick führt ins Portal.</p>' +
      '<p>Mit Konto wird dein Spielstand im Konto gespeichert und ist auf jedem Gerät da. Warst du auf einem anderen Gerät schon weiter, gilt der weitere Stand. An einem geteilten PC werden die Stände verschiedener Konten nie gemischt. Verwende ein <b>Pseudonym</b> – dein echter Name bleibt auf dem Gerät.</p>' +
      '<p>Oben auf der Karte stehen die <b>Vorgaben vom Dozent</b>, mit Frist; ist die Frist vorbei und noch etwas offen, wird sie rot. Gesperrt wird nichts – vorgegebene Stationen sind immer offen.</p>' +
      '<p><b>Sterne:</b> Jede gelöste Aufgabe gibt 1 bis 3 Sterne – 3 ohne Fehlversuch und ohne Tipp, 2 mit höchstens zwei Fehlversuchen und einem Tipp, 1 sobald du einen Sollwert aufgedeckt oder die Lösung angesehen hast. Wer eine Aufgabe nochmals sauber löst, verbessert seine Sterne.</p>' +
      '<p><b>Messwerte einzeln:</b> Im Messprotokoll wird jeder Wert für sich geprüft (✓ richtig, ✗ falsch, ○ offen). Richtige Werte bleiben stehen. Nach zwei falschen Eingaben an einem Wert kannst du seinen <b>Sollwert aufdecken</b> (mit Rechenweg) – er zählt dann als erledigt. Die Aufgabe ist gelöst, sobald die Schaltung alle Tests besteht und jeder Wert richtig oder aufgedeckt ist.</p>' +
      '<p><b>Vorführen:</b> In Messaufgaben zeigt der Knopf „Vorführen“ auf der Werkbank an einem Beispiel, wie gemessen wird: Messart und Bereich, die Spitzen gleiten zu den Buchsen, Anzeige, dann der Rechenweg Schritt für Schritt – mit Tempo, Pause, Einzelschritt und Abbrechen. Dein Aufbau bleibt unverändert; die Vorführung zählt wie ein Tipp. In Prüfung und Live-Challenge gibt es sie nicht.</p>' +
      '<p><b>Lösung ansehen:</b> Nach zwei gescheiterten Prüfungen erscheint der Knopf „Lösung ansehen“: Referenzschaltung, alle Sollwerte und der Rechenweg. Ansehen schaltet nichts frei – bauen und messen musst du selbst; die Station zählt dann mit höchstens 1 Stern. In Prüfung und Live-Challenge gibt es keine Lösung.</p>' +
      '<p><b>Für Lehrpersonen:</b> Das Dozenten-Konto legt der Admin an. Im Portal unter <b>Leitstand</b>: Klassen anlegen, Klassencode weitergeben oder Konten erzeugen (Zugangszettel drucken), Passwörter zurücksetzen, Fortschritt und Schaltungen der Lernenden ansehen und <b>Vorgaben</b> machen. Wer mit einem Dozenten-Konto angemeldet ist, hat im Labor automatisch den <b>Dozentenmodus</b>: alle Stationen offen, Sprungliste auf der Karte, Freie Werkbank mit allen Bauteilen.</p>' },
    { id: 'live', title: 'Live-Challenge', html:
      '<p>Die Lehrperson startet im Portal eine <b>Live-Challenge</b> und zeigt den vierstelligen Code am Beamer. Du trittst im Portal unter <b>Live-Challenge</b> bei; die Aufgabe erscheint bei allen gleichzeitig, sobald die Lehrperson startet.</p>' +
      '<ul><li><b>Sprint:</b> alle lösen dieselbe Aufgabe vom Startaufbau aus.</li><li><b>Störungsjagd:</b> auf dem Tisch liegt ein fehlerhafter Aufbau. Finde die Ursache – mit Messgerät, Strom-Anzeige und Zeitlupe – und behebe sie.</li></ul>' +
      '<p>Punkte gibt es fürs Lösen; schnelle Lösungen bekommen mehr, jeder Fehlversuch und jeder Tipp kostet etwas. Die Challenge verändert deinen Spielstand nicht.</p>' },
    { id: 'pruefung', title: 'Prüfung und Zertifikat', html:
      '<p>Im Portal unter <b>Zertifikate</b> legst du eine echte <b>Prüfung</b> ab: <b>Grundstufe</b> (Kapitel 1–10) und <b>Profi-Stufe</b> (Kapitel 11–15). Voraussetzung: mindestens 80 % der Aufgaben der Stufe gelöst und die Boss-Aufgabe bestanden – oder die Lehrperson öffnet eine <b>Prüfung unter Aufsicht</b> und nennt dir den Code.</p>' +
      '<p>Die Prüfung besteht aus Schaltungsaufgaben (70 %) und Theoriefragen (30 %). Die Aufgaben sind neu und für jede Person anders. Die Zeit läuft auf dem Server. Mit <b>Testen</b> prüfst du die sichtbaren Tests im Browser, mit <b>Abgeben</b> bewertet der Server Schaltung und Messwerte – auch mit verdeckten Tests. Du darfst mehrfach abgeben, es zählt die letzte Abgabe. Tipps gibt es keine; Handbuch, Datenblätter und Messgeräte sind erlaubt.</p>' +
      '<p>Bestanden ist ab 70 %, ab 90 % mit Auszeichnung. Danach stellst du das <b>Zertifikat</b> aus: mit deinem Namen, Prüfcode und QR-Code. Unter der Adresse auf dem Zertifikat kann jede Person die Echtheit prüfen. Du kannst das Zertifikat jederzeit zurückziehen – dann wird der Name gelöscht.</p>' },
    { id: 'karte', title: 'Karte und Abzeichen', html:
      '<p>Die Karte ist in <b>vier Teile</b> gegliedert: <b>I</b> Elektrotechnische Grundlagen (Kapitel 1–4), <b>II</b> Digitaltechnik Grundlagen (5–8), <b>III</b> Kombinatorik und Anzeigen (9–10) – zusammen die <b>Grundstufe</b> – und <b>IV</b> Zeitverhalten und Praxis (11–15), die <b>Profi-Stufe</b>. Dazu <b>Teil V – Vertiefung Messtechnik</b> (Kapitel 16): eine Ergänzung zu Teil I, offen sobald Kapitel 4 abgeschlossen ist; sie zählt nicht zu Abzeichen oder Zertifikat. Dort ziehst du die Messspitzen auf der Werkbank selbst, schliesst den Tastkopf des Oszilloskops an und wählst den Messbereich von Hand (siehe „Multimeter“ und „Oszilloskop“).</p>' +
      '<p>Jede Kachel zeigt ein <b>Symbol zum Inhalt</b> – das prägende Bauteil oder ein Bild zum Thema –, darunter Nummer und Titel und unten die Sterne bzw. den Zustand. Die Kachel mit „hier weiter“ ist deine nächste Station. Theorien bestehst du ab 80 % richtigen Antworten, Aufgaben mit „Prüfen“. Rot umrandet sind die <b>Boss-Aufgaben</b>.</p>' +
      '<p><b>Abzeichen Grundstufe:</b> nach der Boss-Aufgabe 10.10 „Das Codeschloss“. <b>Abzeichen Profi-Stufe:</b> nach der Boss-Aufgabe 15.10 „Die Antriebsstation“. Beide erscheinen auf der Karte am Ende ihres Teils; mit „Anzeigen“ trägst du deinen Namen ein und kannst sie drucken (A4 quer). Das geprüfte <b>Zertifikat</b> gibt es im Portal – siehe „Prüfung und Zertifikat“.</p>' },
    { id: 'multimeter', title: 'Multimeter', html:
      '<p>Wähle einen Messbereich (V, A, Ω). Danach setzen Klicks auf Anschlüsse die Messspitzen: zuerst <b style="color:#ff6b61">rot (+)</b>, dann <b>schwarz (COM)</b>.</p>' +
      '<p>Auf der Werkbank steht dasselbe Gerät: Drehschalter anklicken, die Messkabel führen zu den Prüfspitzen.</p>' +
      '<ul><li><b>V⎓</b> – Gleichspannung, parallel zum Bauteil. Innenwiderstand 10 MΩ. Bei schneller Wechselspannung zeigt das Gerät den Mittelwert (beim Sinus 0 V).</li>' +
      '<li><b>V~</b> – Wechselspannung (nur der Wechselanteil). Zwei Messverfahren: <b>Mittelwert (AVG)</b> misst den Gleichrichtwert und rechnet ihn auf den Sinus-Effektivwert um – bei Rechteck oder Dreieck zeigt es falsch. <b>Echt-Effektivwert (TRMS)</b> stimmt für jede Kurvenform.</li><li><b>A</b> – in Reihe: Leitung lösen, Spitzen in die Lücke. Innenwiderstand 0,1 Ω, Sicherung 10 A.</li><li><b>A~</b> – Wechselstrom in Reihe (Effektivwert mit TRMS bzw. AVG wie bei V~), gleiche Sicherung wie A⎓: parallel zu einer Quelle brennt sie durch. A⎓ an Wechselstrom zeigt nur den Mittelwert (≈ 0), A~ an Gleichstrom nur den Wechselanteil (0) – das Gerät sagt dir, welche Messart passt.</li><li><b>Ω</b> – nur spannungsfrei. „0L“ = Unterbrechung.</li></ul>' +
      '<p>Wie ein echtes Gerät zeigt es 4 Stellen mit automatischer Bereichswahl, hat eine kleine Messabweichung (+0,2 %) und die letzte Stelle kann um 1 Digit schwanken.</p>' +
      '<p><b>Neue Bedienung in der Vertiefung Messtechnik (Kapitel 16):</b> Auf der Werkbank liegen die Messspitzen vor dem Gerät. Du <b>ziehst</b> sie mit der Maus (oder dem Finger) an die Buchse – loslassen daneben legt sie zurück. Ein Klick auf eine Buchse verbindet dort immer Leitungen. Unter dem Drehschalter wählst du den <b>Messbereich</b> von Hand (AUTO oder z. B. 200mV, 2V, 20V …): Ist der Messwert grösser als der Bereich, zeigt das Gerät <b>OL</b>; ein zu grosser Bereich verschenkt Stellen. Das LCD zeigt „MAN 20V“ statt AUTO. Ausgeschaltet bleiben die Spitzen stecken.</p>' },
    { id: 'oszi', title: 'Oszilloskop', html:
      '<p>Das Oszilloskop zeichnet die Spannung zwischen den Multimeter-Spitzen (oder rot gegen Masse) über die Zeit auf – ab dem Einschalten. Ideal für Lade-/Entladekurven, Taktsignale und Wechselspannungen. Auf der Werkbank startet die Taste RUN am Gerät die Aufnahme.</p>' +
      '<p>In der <b>Vertiefung Messtechnik</b> (Kapitel 16) hat das Oszilloskop einen eigenen <b>Tastkopf</b> (gelb, CH1) und einen <b>Erdungsclip</b> (schwarz), die vor dem Gerät liegen: beide an die Schaltung ziehen, dann RUN. Ohne Tastkopf bleibt der Schirm dunkel („Tastkopf anschliessen“). Multimeter und Oszilloskop können so gleichzeitig an verschiedenen Stellen messen.</p>' },
    { id: 'bauteile', title: 'Bauteile', html:
      '<dl><dt>Spannungsquelle</dt><dd>Ideale Quelle mit kleinem Innenwiderstand.</dd><dt>LED</dt><dd>Leuchtet ab U<sub>F</sub> (rot 1,8 V … blau 3,0 V), max. 30 mA.</dd>' +
      '<dt>Logikgatter</dt><dd>5-V-Logik, Schaltschwelle 2,5 V. Versorgung ist intern, brauchen aber eine Masse (⏚).</dd><dt>Kondensator</dt><dd>Lädt über einen Widerstand mit τ = R · C.</dd>' +
      '<dt>Wechselspannungsquelle</dt><dd>Kleiner Funktionsgenerator: Scheitelwert Û, Frequenz und Kurvenform (Sinus, Rechteck, Dreieck) einstellbar. Effektivwert beim Sinus: U = Û / √2.</dd>' +
      '<dt>Taktgeber</dt><dd>Rechteck 0/5 V mit einstellbarer Frequenz – für Blinker, Zähler und Impulsgeber.</dd>' +
      '<dt>Pegelschalter (E)</dt><dd>Eingang am Experimentierboard: Klick schaltet zwischen 0 und 1 (5 V). Öffner-Taster (z. B. Stopp, Not-Halt) stehen in Ruhe auf 1.</dd>' +
      '<dt>Logikanzeige (L)</dt><dd>Leuchtet bei 1 (ab 2,5 V). Belastet den Ausgang praktisch nicht.</dd>' +
      '<dt>BCD-7-Segment-Decoder (IC)</dt><dd>Eingänge A (1), B (2), C (4), D (8) → Segmentausgänge a … g. Codes 10 … 15 bleiben dunkel.</dd>' +
      '<dt>7-Segment-Anzeige (AZ)</dt><dd>Gemeinsame Kathode: Segment leuchtet bei 1. a oben, im Uhrzeigersinn b … f, g in der Mitte.</dd>' +
      '<dt>Flipflops (FF)</dt><dd>D-, JK- und T-Flipflop, übernehmen bei der <b>steigenden Flanke</b> an C. Ausgänge Q und Q̄. D: Q = D. JK: 10 setzen, 01 rücksetzen, 11 kippen. T: kippt bei T = 1.</dd>' +
      '<dt>Diode (V)</dt><dd>Silizium, Schleusenspannung ca. 0,7 V. Ring = Kathode. Auch als Freilaufdiode am Motor (parallel, Kathode an Plus).</dd>' +
      '<dt>Z-Diode (Z)</dt><dd>In Sperrrichtung betrieben hält sie die Z-Spannung (einstellbar, Standard 5,1 V). Immer mit Vorwiderstand.</dd>' +
      '<dt>NPN-Transistor (Q)</dt><dd>Basis, Kollektor, Emitter. Gesperrt, aktiv (I<sub>C</sub> = β · I<sub>B</sub>, β einstellbar) oder in Sättigung (U<sub>CE</sub> klein). Als Schalter mit Basiswiderstand übersteuern.</dd>' +
      '<dt>Motor (M)</dt><dd>Gleichstrommotor, Nenndaten 6 V / 0,3 A, im Simulator als Wicklungswiderstand (Standard 20 Ω) nachgebildet: Die Drehzahl folgt dem Strom, Umpolen kehrt die Drehrichtung um.</dd>' +
      '<dt>Verdeckte Defekte</dt><dd>In Fehlersuch-Aufgaben kann ein Widerstand, eine Lampe oder ein Motor innen unterbrochen sein – von aussen sieht man nichts. Nur Messen hilft: volle Spannung über dem Bauteil, aber kein Strom.</dd></dl>' }
  ];
})(typeof window !== 'undefined' ? window : globalThis);
