/* ===== Digital Quest Portal: Anleitungen für Lernende, Dozenten und Admin (#/anleitung/…) – Aufbau wie im SPS-Quest-Portal ===== */
(function(){
'use strict';
const P = window.DQP, $ = id => document.getElementById(id);
const step = (n, t, body) => '<div class="man-step"><div class="man-n">' + n + '</div><div><h3>' + t + '</h3>' + body + '</div></div>';
// Weitere Schritte (z. B. Zertifikat mit Prüfung) hängen sich ein: P.manual.lernende.push({ title, html })
const EXTRA = { lernende: [], dozenten: [], admin: [] };
const BASE = {
  lernende: [
    ['Ein Tor wählen', '<p>Auf der Titelseite stehen drei Tore: das <b>Labor</b> (die Quest mit 15 Kapiteln), die <b>Übungswerkstatt</b> (fertige Schaltungen, nur messen) und die <b>Freie Werkbank</b> (frei bauen ohne Auftrag). Ein Klick startet direkt im Browser — auch ohne Konto und nach dem ersten Laden auch offline.</p>'],
    ['Anmelden mit Klassencode', '<p>Deine Lehrperson gibt dir entweder ein <b>fertiges Konto</b> (Benutzername + Startpasswort) oder einen <b>6-stelligen Klassencode</b>.</p><ul><li><b>Konto erhalten:</b> Oben rechts <i>Anmelden</i> → Benutzername und Startpasswort → beim ersten Login ein eigenes Passwort wählen.</li><li><b>Klassencode:</b> <i>Anmelden</i> → <i>[KLASSENCODE]</i> → Code eingeben, ein <b>Pseudonym</b> wählen (kein echter Name!) und ein Passwort festlegen.</li></ul><p>Mit Konto wandert dein Fortschritt mit — auf jedes Gerät. Hast du vorher schon ohne Konto gespielt, fragt das Labor beim ersten Login, ob dieser Stand übernommen werden soll.</p>'],
    ['Im Labor', '<ul><li>Jedes Kapitel: <b>Theorie A</b> → Aufgaben 1–5 → <b>Theorie B</b> → Aufgaben 6–10. Eine Theorie ist bestanden ab 4 von 5 richtigen Antworten.</li><li>Bauteile aus der Palette holen, Anschlüsse anklicken und verbinden, Schalter betätigen. Die Schaltung wird <b>live simuliert</b> – im Schaltplan oder auf der <b>Werkbank</b> (Knopf in der Werkzeugleiste).</li><li><b>Messen</b> wie im Labor: Multimeter (V, A, Ω) und Oszilloskop. Messwerte trägst du ins Messprotokoll ein, dann <i>Prüfen</i>.</li><li>Festgefahren? <i>Tipp 1</i> und <i>Tipp 2</i> helfen weiter (kosten Sterne). Das <i>Handbuch</i> erklärt jedes Bauteil; fahr mit der Maus über ein Bauteil für das Datenblatt.</li><li>Für jede Aufgabe gibt es bis zu <b>drei Sterne</b>: ohne Fehlversuch und ohne Tipp.</li></ul>'],
    ['Vorgaben deiner Lehrperson', '<p>Hat deine Lehrperson dir oder der Klasse etwas vorgegeben, steht es oben auf der Laborkarte unter <b>Vorgaben vom Dozent</b> – mit Frist. Vorgegebene Stationen sind immer offen, auch wenn du noch nicht so weit bist. Ist die Frist vorbei, wird der Eintrag rot; gesperrt wird nichts.</p>'],
    ['Live-Challenge im Unterricht', '<p>Wenn deine Lehrperson eine Challenge startet, steht am Beamer ein <b>4-stelliger Code</b>. Im Portal <i>Live-Challenge</i> → Code eingeben → das Labor öffnet sich und wartet auf den Start. Beim <b>Sprint</b> lösen alle dieselbe Aufgabe, bei der <b>Störungsjagd</b> ist die Schaltung schon aufgebaut – mit einem Fehler, den du findest und behebst. Schnell sein bringt Punkte, Fehlversuche und Tipps kosten welche.</p>'],
    ['Konto und Daten', '<ul><li>Unter <i>Konto</i> änderst du dein Passwort oder löschst dein Konto samt Spielstand.</li><li>Deine Lehrperson sieht deinen Fortschritt, deine Sterne und deine Schaltungen mit Messwerten — sonst nichts. Es gibt keine E-Mail und keine echten Namen.</li><li>Passwort vergessen? Deine Lehrperson kann es zurücksetzen.</li><li><i>Abmelden</i> lädt deinen Stand hoch und entfernt ihn aus dem Browser — wichtig an gemeinsam genutzten Schulrechnern.</li></ul>'],
    ['Feedback und Fehler melden', '<p>Unten links ist überall – im Portal und im Labor – der Knopf <b>💬</b>. Damit schickst du jederzeit ein kurzes <b>Feedback</b> oder meldest einen <b>Fehler</b>. Wo du gerade bist (Aufgabe) und dein Benutzername werden automatisch mitgeschickt; ohne Anmeldung bleibt die Meldung anonym.</p>']
  ],
  dozenten: [
    ['Erster Login', '<p>Du bekommst deinen Benutzernamen und ein <b>Startpasswort</b> vom Admin. Oben rechts <i>Anmelden</i> → einloggen → beim ersten Login ein eigenes Passwort setzen. Danach landest du im <b>Leitstand</b>.</p>'],
    ['Klasse anlegen', '<p><i>Leitstand</i> → <i>Neue Klasse</i> → Name eingeben (z. B. „AT1A – Elektrotechnik“). Jede Klasse bekommt einen <b>Klassencode</b>.</p>'],
    ['Lernende aufnehmen — zwei Wege', '<ul><li><b>Konten erzeugen:</b> In der Klasse ein Präfix (z. B. <code>at1a_</code>) und eine Anzahl eingeben → <i>Nummeriert erzeugen</i>, oder <i>Namensliste …</i> mit einem Pseudonym pro Zeile. Die Startpasswörter werden <b>nur einmal</b> angezeigt → <i>Zugangszettel drucken</i> und verteilen.</li><li><b>Selbstanmeldung:</b> Häkchen <i>Selbstanmeldung offen</i> setzen und den Code bzw. den Direktlink an die Tafel schreiben. Lernende wählen ihr Pseudonym selbst. Danach die Selbstanmeldung wieder schliessen oder mit <i>Neuen Code erzeugen</i> den alten Code ungültig machen.</li></ul><p class="muted">Bitte nur Pseudonyme verwenden — keine echten Namen.</p>'],
    ['Fortschritt verfolgen', '<ul><li>Die Klassenliste zeigt pro Konto Stand, Fortschrittsbalken, Aufgaben, Theorien, Sterne und letzte Aktivität.</li><li>Ein Klick auf ein Pseudonym öffnet das Aufgabenraster: Farbe = Sterne, Klick auf eine Zelle zeigt die <b>Schaltung</b> (Lösung oder Entwurf) als bedienbare Mini-Schaltung mit Stromfluss, dazu das Messprotokoll.</li><li><span class="pill warn">Start-PW</span> heisst: Das Startpasswort wurde noch nicht geändert.</li><li><i>Passwort</i> erzeugt ein neues Startpasswort, <i>✕</i> löscht ein Konto samt Spielstand.</li></ul>'],
    ['Vorgaben mit Frist', '<ul><li>In der Klassenansicht unter <i>Vorgaben</i>: ganze <b>Kapitel</b> ankreuzen oder aufklappen und einzelne <b>Stationen</b> wählen (auch aus der Übungswerkstatt).</li><li>Für die <b>ganze Klasse</b> oder <b>einzelne Lernende</b>, optional mit <b>Frist</b>.</li><li>Die Lernenden sehen die Vorgabe oben auf ihrer Laborkarte. Vorgegebene Stationen sind für sie immer offen.</li><li>Die Liste zeigt je Vorgabe, wer sie erledigt hat (grün), und markiert überfällige rot. Gesperrt wird nichts.</li></ul>'],
    ['Live-Challenge durchführen', '<ol><li><i>Leitstand</i> → <i>Neue Live-Challenge</i>.</li><li>Modus wählen: <b>Sprint</b> (alle lösen dieselbe Aufgabe) oder <b>Störungsjagd</b> (eine aufgebaute Schaltung mit eingebautem Fehler). Kapitel und Aufgabe bzw. Störung, Dauer und optional die Klasse wählen.</li><li>Die <b>Beamer-Ansicht</b> öffnet sich mit einem 4-stelligen Code. Lernende treten über <i>Live-Challenge</i> im Portal bei; die Aufgabe bleibt bis zum Start verborgen.</li><li><i>Start</i> → Countdown und Live-Rangliste (Pseudonym, Zeit, Versuche, Tipps, Punkte).</li><li>Am Ende Siegerehrung mit Podest. Mit <i>Lösung zeigen</i> besprichst du eine Schaltung anonym neben der Musterschaltung.</li></ol>'],
    ['Im Labor alles offen', '<p>Mit einem Dozenten-Konto sind im Labor <b>alle Stationen offen</b>. Oben auf der Laborkarte steht die Liste <i>Springe zu …</i> für jede Aufgabe, und die Freie Werkbank hat alle Bauteile. So bereitest du den Unterricht vor oder führst am Beamer vor.</p>'],
    ['Feedback auswerten', '<p>Meldungen über den Knopf <b>💬</b> (Feedback und Fehler, mit Aufgabe und Pseudonym) stehen im Menü <i>Meldungen</i> bzw. im Leitstand unter <i>Feedback und Fehlermeldungen</i>, filterbar nach Typ.</p>'],
    ['Aufräumen', '<p><i>Klasse löschen</i> entfernt die Klasse mit <b>allen Konten, Spielständen und Vorgaben</b> endgültig — zum Beispiel am Ende des Semesters.</p>']
  ],
  admin: [
    ['Admin-Zugang', '<p>Benutzername und Passwort des Admins kommen aus den Worker-Secrets <code>ADMIN_USER</code> und <code>ADMIN_PASSWORD</code> (Cloudflare-Dashboard → Worker <b>digital-quest</b> → Einstellungen → Variablen und Secrets). Beim ersten Login wird das Admin-Konto automatisch angelegt. Geändert wird dieses Passwort nur dort, nicht im Portal.</p><p>Der Admin kann zugleich <b>Dozent</b> sein: Menü <i>Leitstand</i> → eigene Klassen, Konten, Vorgaben, Live-Challenge.</p>'],
    ['Dozenten anlegen', '<p><i>Administration</i> → <i>Neuer Dozent</i> → Benutzername (z. B. Kürzel) → <i>Anlegen</i>. Das <b>Startpasswort</b> wird nur einmal angezeigt; die Dozentin oder der Dozent muss es beim ersten Login ändern.</p>'],
    ['Meldungen', '<p>Unter <i>Meldungen</i> siehst du alle Feedbacks und Fehlermeldungen aus Portal und Labor (Knopf <b>💬</b>) mit Aufgabe, Benutzer und Browser. Filter nach Typ und Ort; <i>erledigt</i> abhaken oder löschen.</p>'],
    ['Dozenten verwalten', '<ul><li>Die Kennzahlen oben zeigen Dozenten, Klassen, Lernende und gespeicherte Spielstände.</li><li><i>Passwort</i> erzeugt ein neues Startpasswort (alle Geräte werden abgemeldet).</li><li><i>✕</i> löscht einen Dozenten — <b>mit allen Klassen und Lernendenkonten</b>. Das kann nicht rückgängig gemacht werden.</li></ul>'],
    ['Sicherheit und Datenschutz', '<ul><li>Passwörter werden nur gehasht gespeichert (PBKDF2). Nach 5 Fehlversuchen pro Konto bzw. 40 pro IP in 15 Minuten wird der Login für 15 Minuten gesperrt.</li><li>Konten bestehen nur aus Pseudonym und Passwort — keine E-Mail, keine echten Namen.</li><li>Vor dem Betrieb <b>Impressum</b> und <b>Datenschutzerklärung</b> ausfüllen: In <code>dev/portal/impressum.html</code> und <code>datenschutz.html</code> alle <code>[[…]]</code>-Platzhalter ersetzen, neu bauen und rechtlich prüfen lassen.</li></ul>'],
    ['Betrieb und Updates', '<ul><li>Hosting: Cloudflare Worker <b>digital-quest</b> mit Workers Builds und D1-Datenbank <b>digitalquest</b>. Die Tabellen legt der Code selbst an.</li><li>Jeder Push nach <code>main</code> auf GitHub wird automatisch gebaut und veröffentlicht. Den Build-Status zeigt der GitHub-Check „Workers Builds: digital-quest“.</li><li>Nach einem Update laden Browser die neue Version beim nächsten Besuch (Service Worker); notfalls hilft <kbd>Strg</kbd>+<kbd>Shift</kbd>+<kbd>R</kbd>.</li><li>Den aktuellen Projektstand beschreibt <code>docs/STAND.md</code> im Repository.</li></ul>']
  ]
};
const TABS = [
  { id:'lernende', label:'Lernende', icon:'🎮', title:'Anleitung für Lernende', lead:'So arbeitest du im Labor, meldest dich mit deiner Klasse an und machst bei einer Live-Challenge mit.' },
  { id:'dozenten', label:'Dozenten', icon:'🧑‍🏫', title:'Anleitung für Dozentinnen und Dozenten', lead:'Klassen anlegen, Konten verteilen, Fortschritt verfolgen, Vorgaben machen und Live-Challenges am Beamer durchführen.' },
  { id:'admin', label:'Admin', icon:'🛠️', title:'Anleitung für den Admin', lead:'Das Admin-Konto verwaltet die Dozentenkonten. Lernende und Klassen verwalten die Dozenten selbst.' }
];
function view(m){
  const tab = TABS.find(t => t.id === (m && m[1])) || TABS[0];
  const steps = BASE[tab.id].concat(EXTRA[tab.id].map(x => [x.title, x.html]));
  $('view').innerHTML = '<div class="console man"><div class="crumbs"><a href="#/">HALLE</a> / ANLEITUNG</div><h1>' + tab.title + '</h1><p class="lead">' + tab.lead + '</p>' +
    '<p class="man-ww">🧭 Neu hier? Der <a href="#/wegweiser">Wegweiser</a> erklärt jeden Menüpunkt in einem Satz und bietet einen kurzen Rundgang.</p>' +
    '<div class="man-tabs" role="tablist">' + TABS.map(t => '<a role="tab" aria-selected="' + (t === tab) + '" class="man-tab' + (t === tab ? ' active' : '') + '" href="#/anleitung/' + t.id + '"><span aria-hidden="true">' + t.icon + '</span> ' + t.label + '</a>').join('') + '</div>' +
    '<div class="panel man-body">' + steps.map((s, i) => step(i + 1, s[0], s[1])).join('') + '</div></div>';
}
P.manual = EXTRA;
P.routes.push({ re: /^#\/anleitung(?:\/(lernende|dozenten|admin))?$/, view });
P.nav.push({ href:'#/anleitung', label:'Anleitung', before:'ende', show: () => true });
P.home.push(() => '<section class="man-home" aria-label="Anleitungen"><h2>Anleitungen</h2><div class="man-cards">' +
  '<a class="man-card" href="#/anleitung/lernende"><span class="ic" aria-hidden="true">🎮</span><b>Lernende</b><span>Im Labor arbeiten, mit Klassencode anmelden, Live-Challenge beitreten</span></a>' +
  '<a class="man-card" href="#/anleitung/dozenten"><span class="ic" aria-hidden="true">🧑‍🏫</span><b>Dozenten</b><span>Klassen, Konten, Fortschritt, Vorgaben, Live-Challenge am Beamer</span></a>' +
  '<a class="man-card" href="#/anleitung/admin"><span class="ic" aria-hidden="true">🛠️</span><b>Admin</b><span>Dozenten verwalten, Sicherheit, Betrieb</span></a>' +
  '</div></section>');
})();
